# Author: Saurav Gupta
# Date Created: Sep. 17, 2019

"""
This file is for removing hard codded values of some file names, signal names etc..
"""

SIGNAL_FILE = "all_signals.h5"
SIGNAL_FILE_TITLE = "Signal File"

CLOUD_SIGNAL_PREFIX = "cloud"
CLOUD_SIGNAL_GROUP_NAME = "cloud"
CLOUD_SIGNAL_GROUP_TITLE = "Cloud"
CLOUD_SIGNAL_TABLE_NAME = "cloud_signals"
CLOUD_SIGNAL_TABLE_TITLE = "Cloud Signals"

HARDWARE_SIGNAL_PREFIX = "hardware"
HARDWARE_SIGNAL_GROUP_NAME = "hardware"
HARDWARE_SIGNAL_GROUP_TITLE = "Hardware"
HARDWARE_SIGNAL_TABLE_NAME = "hw_signals"
HARDWARE_SIGNAL_TABLE_TITLE = "Hardware Signals"

HARDWARE_SIGNAL_LENGTH = 9

QUEUE_WAIT_TIME = 0.01  # In seconds

CLOUD_SIGNAL_NO_OF_PARTS = 5

CLOUD_SIGNAL_LIGHT_ENTITY = "light"
CLOUD_SIGNAL_DUSTBIN_ENTITY = "dustbin"
CLOUD_SIGNAL_TANK_ENTITY = "water_tank"
CLOUD_SIGNAL_MOTOR_ENTITY = "motor"

CLOUD_SIGNAL_LIGHT_ENTITY_NUMBER = 1
CLOUD_SIGNAL_DUSTBIN_ENTITY_NUMBER = 2
CLOUD_SIGNAL_TANK_ENTITY_NUMBER = 3
CLOUD_SIGNAL_MOTOR_ENTITY_NUMBER = 4

ON = "on"
OFF = "off"
